spring.application.name=backend

# Conexión a la base de datos PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/faro

spring.datasource.username=faro
spring.datasource.password=faro

# Comportamiento de Hibernate (igual al que tienen en Docker)
spring.jpa.hibernate.ddl-auto=update
